# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae5bcce615730dd1da074600332bbc6c5ee4d36d852d44b2c5337c8d7ec0de29244912201c481f86c669c2eb64566fd5089e20eab839d7d65b43cfa0d91fe29b

test:
  secret_key_base: 511c4326e221102db0885733dd3e6f01379e04907196bd8e5c392d61b1a763d0e006241b208c2baca9d51a70e9487e206038ba6a90f447309db88c7b42090882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
